# Generated by Django 6.0.2 on 2026-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=255),
        ),
    ]
