# Generated by Django 6.0.2 on 2026-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_book_cover_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='externalRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='ratingsCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
