# Generated by Django 6.0.2 on 2026-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_book_externalrating_book_isfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isCustom',
            field=models.BooleanField(default=False),
        ),
    ]
