# Generated by Django 6.0.2 on 2026-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_book_iscustom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsession',
            name='duration',
            field=models.IntegerField(help_text='Тривалість у секундах'),
        ),
        migrations.CreateModel(
            name='ReadingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_cycles', to='tracker.book')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
