# Generated by Django 6.0.2 on 2026-04-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_readingsession_duration_readingcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='Активний читач', help_text='Короткий статус користувача', max_length=100, null=True),
        ),
    ]
