# Generated by Django 6.0.2 on 2026-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingsession',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='book',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='pages_read',
            field=models.IntegerField(default=0, help_text='Кількість прочитаних сторінок за сесію'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='duration',
            field=models.IntegerField(blank=True, default=0, help_text='Тривалість у секундах', null=True),
        ),
    ]
