# Generated by Django 6.0.2 on 2026-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_readingsession_options_book_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text="Обов'язкове поле. 150 символів або менше.", max_length=150),
        ),
    ]
